name: Build and Deploy Flask App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Docker Hub (optional, if pushing to Docker Hub)
      #- name: Log in to Docker Hub
        #uses: docker/login-action@v2
        #with:
          #username: ${{ secrets.DOCKER_USERNAME }}
          #password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t flask-app .

      # Push the Docker image to Docker Hub (optional)
      #- name: Push Docker image
        #run: |
          #docker tag flask-app ${{ secrets.DOCKER_USERNAME }}/flask-app:latest
          #docker push ${{ secrets.DOCKER_USERNAME }}/flask-app:latest

      # Test the Docker container
      - name: Run and test container
        run: |
          docker run -d -p 5000:5000 --name flask-app-test flask-app
          sleep 10 # Wait for the container to start
          curl -f http://localhost:5000 || (docker logs flask-app-test && exit 1)
          docker stop flask-app-test
          docker rm flask-app-test
